### PR TITLE
Modify displays

### PR DESCRIPTION
**Pull request by rioorinoco**
以下、日本語表記に変更しています
・distributors
・agencies
・items
・corporates
確認お願いします

### CODE REVIEW

**Comment by piacerex** [comment]
1.The following files are not related to this change, so don't commit:
- README.md
- lib/basic/accounts/user_notifier.ex
- lib/basic_web/templates/user_registration/done.html.eex 

2.The following items don't need to be validate_required in lib/basic/corporates/corporate.ex changeset:
- postal
- prefecture
- city
- address1
- address2
- tel

3.The following items don't need to be validate_required in lib/basic/items/item.ex changeset:
- detail
- distributor_id
- price
- start_date
- end_date
- open_date
- close_date
- is_open
- area
- occupation
- alls
- stocks

4.The following pages, please write "<!-" and "->" on the previous or next lines when comment-out:
- lib/basic_web/live/agency_live/index.html.leex 
- lib/basic_web/live/corporate_live/index.html.leex 
- lib/basic_web/live/distributor_live/index.html.leex 
- lib/basic_web/live/item_live/index.html.leex

**Comment by rioorinoco** [comment]
b801827400d35e68a6113891b07c5fa8e67e34fd

**Comment by rioorinoco** [comment]
#2

**Comment by rioorinoco** [comment]
6f4334918af611faeaf3da8393a8f947f8109ed3

**Comment by piacerex** [comment]
The following items have been renamed.
(Please follow this naming in the future.)

## items
- Image -> イメージ
- ディストリビューターID -> 卸者ID
- 募集中か -> 募集中か？ ... Since something like is_xxx is an item that asks whether it's xxx or not, please add "?"

## distributors
- 名称 -> 卸者名称

## agencies
- 名称 -> 代理店名称
- ディストリビューターID -> 卸者ID

**Pull request merged**
