### PR TITLE
Change corporate into organization

### PR DESCRIPTION
**Pull request by rioorinoco**
確認、お願いします。
README.md のルールがわからなかったので、# でコメントアウトして下の行に新しい mix ..... を挿入しています。

### CODE REVIEW

**Comment by rioorinoco** [comment]
grantsの新規作成画面の表記が、user_id（英語表記） のままでした。
grants機能を作り込んでいるので、次のプルリクで修正します。

**Comment by piacerex** [comment]
1.README.md comment-outs are unnecessary.
  README.md's spacing rule is "item caterorise by similar item", but don't need rewrite this because rewrite by me.
  Please delete comment-out part only.

2.Would you forgot do deleteing following files?:
- lib/basic/corporaties/corporatie.ex
- under lib/basic/_web/live/corporate_live/
- test/basic/corporates_test.exs 
- test/basic_web/live/corporate_live_test.exs 

3.The following files updating are duplicate, delete it:
- test/basic/agencies_test.exs 
- test/basic/distributors_test.exs 
- test/basic/grants_test.exs 

4.The corporates routing comment-outs are unnecessary.

**Comment by rioorinoco** [comment]
上のコメントの対応をしました。
うまくできてるといいけど。

**Comment by piacerex** [comment]
1.The following files are unnecessary, don't commit it:
- priv/repo/migrations/20210819075310_create_grants.exs
- priv/repo/migrations/20210819075514_create_distributors.exs 
- priv/repo/migrations/20210819075620_create_agencies.exs 

2.The following file descriptions are unnecessary, delete it:
- priv/repo/migrations/20210819074800_drop_old_corporate_related_tables.exs
```
  drop_if_exists table(:grants)
  drop_if_exists table(:distributors)
  drop_if_exists table(:agencies)
```

3.Please restore the following files, thies diffs should not occure, so I will check it once:
- test/basic/agencies_test.exs 
- test/basic/distributors_test.exs
- test/basic/grants_test.exs

**Pull request merged**
